[project]
name = "brads-bootable"
authors = ["Brad Jones <brad@bjc.id.au>"]
channels = ["https://repo.prefix.dev/brads-forge", "conda-forge"]
description = "A Fedora bootc build for Brads Homelab"
platforms = ["linux-64"]

[tasks]
init = "task init"

[tasks.code]
depends-on = ["init"]
cmd = "code ."

[dependencies]
deno = ">=2.1.9,<2.2"
dprint = ">=0.49.0,<0.50"
oras = ">=1.2.0,<2"
lefthook = ">=1.10.10,<2"
go-shfmt = ">=3.10.0,<4"
cocogitto = ">=6.2.0,<7"
task = ">=3.41.0,<4"
age = ">=1.2.1,<2"
go-sops = ">=3.9.4,<4"
terraform = ">=1.10.5,<2"
nodejs = ">=22.12.0,<22.13"
virtctl = ">=1.4.0,<2"
