# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

dotenv: [".env"]

tasks:
  init:
    desc: Setup dev env
    cmds:
      - lefthook install -f
      - git config pull.rebase true
      - git config core.editor "code --wait"
      - git config commit.template "$PWD/.gitmsgtpl"

  build:image:
    cmds:
      - docker build -t ghcr.io/brad-jones/brads-bootable:dev ./src

  pull:iso:
    cmds:
      - oras pull ghcr.io/brad-jones/brads-bootable/iso:latest -o ./iso

  flux:init:
    vars:
      AGE_KEY:
        sh: gopass -o brads-bootable/age.key
      GH_TOKEN:
        sh: gopass -o brads-bootable/gh.token
    cmds:
      - ssh brad-jones@192.168.254.4 kubectl create secret generic cluster-repo-token --namespace flux-system --from-literal=username=git --from-literal=password={{.GH_TOKEN}}
      - ssh brad-jones@192.168.254.4 kubectl create secret generic cluster-age-key --namespace flux-system --from-literal=age.agekey={{.AGE_KEY}}

  secrets:edit:
    env:
      SOPS_AGE_KEY:
        sh: gopass -o brads-bootable/age.key
    cmds:
      - sops edit ./k8s/secrets.sops.yaml
