# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

dotenv: [".env"]

tasks:
  init:
    desc: Setup dev env
    cmds:
      - lefthook install -f
      - git config pull.rebase true
      - git config core.editor "code --wait"
      - git config commit.template "$PWD/.gitmsgtpl"

  build:image:
    cmds:
      - docker build -t ghcr.io/brad-jones/brads-bootable:dev ./src

  pull:iso:
    cmds:
      - oras pull ghcr.io/brad-jones/brads-bootable/iso:latest -o ./iso

  kluctl:init:
    cmds:
      - podman run --rm -it --privileged --user $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) -v $KUBECONFIG:$KUBECONFIG:ro -e KUBECONFIG ghcr.io/kluctl/kluctl:v2.26.0 controller install -y
