---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik-helm-repo
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-helm-release
spec:
  interval: 1m0s
  chart:
    spec:
      chart: traefik
      version: ">=33.0.0 <34.0.0"
      interval: 1m0s
      sourceRef:
        kind: HelmRepository
        name: traefik-helm-repo
  values:
    hostNetwork: true
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
    service:
      enabled: false
    ports:
      traefik:
        hostPort: 8080
      web:
        hostPort: 80
      websecure:
        hostPort: 443
    gateway:
      listeners:
        web:
          namespacePolicy: All
        websecure:
          namespacePolicy: All
    logs:
      access:
        enabled: true
    globalArguments: []
